[package]
name = "docxium"
version = "0.1.0"
edition = "2024"
description = "Batch operations for python-docx implemented in Rust"
license = "MIT"

[lib]
name = "_core"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.29.3", features = ["abi3-py39"] }
quick-xml = "0.42.0"

[profile.release]
lto = true
codegen-units = 1
